/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as swapSol from "./Swap.sol";
export type { swapSol };
export type { MockToken } from "./MockToken";
export type { Tokens_erc20 } from "./Tokens_erc20";
