/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestToken__factory } from "./TestToken__factory";
export { Tokens_erc20__factory } from "./Tokens_erc20__factory";
